system-ghc: true
install-ghc: false
allow-newer : true


resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/21.yaml


packages:
- .
- ../../../Useful

extra-deps:
- recursion-2.2.5.0

